# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Constellation.delete_all
Season.delete_all

season_a = Season.create(name: "Winter")
season_b = Season.create(name: "Spring")
season_c = Season.create(name: "Summer")
season_d = Season.create(name: "Autumn")

constellation_w1 = Constellation.create(name: "Canis Major", description: "Canis Major is a constellation in the southern sky. Its name means “the greater dog” in Latin. Canis Major represents the bigger dog following Orion, the hunter in Greek mythology. The dog is often depicted pursuing a hare, represented by the constellation Lepus. The smaller dog is represented by the neighboring constellation Canis Minor. Both constellations were first catalogued by Ptolemy in the 2nd century.", image_url: "http://www.seasky.org/constellations/assets/images/canis-major.jpg", season_id: 1)
constellation_w2 = Constellation.create(name: "Canis Minor", description: "Canis Minor is a small constellation in the northern sky. Its name means “the smaller dog” or “lesser dog” in Latin. The constellation represents one of the dogs following Orion, the hunter in Greek mythology. The other dog is represented by the larger neighbouring constellation Canis Major. Both constellations were first catalogued by the Greek astronomer Ptolemy in the 2nd century.", image_url: "http://www.seasky.org/constellations/assets/images/canis-minor.jpg", season_id: 1)
constellation_w3 = Constellation.create(name: "Gemini", description: "Gemini constellation is located in the northern hemisphere of the sky. Its name means “the twins” in Latin. Gemini is one of the zodiac constellations, first catalogued by the Greek astronomer Ptolemy in the 2nd century. The constellation represents the twins Castor and Pollux (Polydeuces), also known as the Dioscuri in ancient times, in Greek mythology. The constellation’s symbol is ♊.", image_url: "http://www.seasky.org/constellations/assets/images/gemini.jpg", season_id: 1)
constellation_w4 = Constellation.create(name: "Orion", description: "Orion constellation is one of the brightest and best known constellations in the night sky. It lies on the celestial equator. Orion has been known since ancient times. The constellation is also known as the Hunter, as it is associated with one in Greek mythology. It represents the mythical hunter Orion, who is often depicted in star maps as either facing the charge of Taurus, the bull, pursuing the Pleiades sisters, represented by the famous open cluster, or chasing after the hare (constellation Lepus) with his two hunting dogs, represented by the nearby constellations Canis Major and Canis Minor.", image_url: "http://www.seasky.org/constellations/assets/images/orion.jpg", season_id: 1)
constellation_w5 = Constellation.create(name: "Taurus", description: "Taurus constellation lies in the northern sky. Its name means “bull” in Latin. The constellation is symbolized by the bull’s head, ♉. Taurus is one of the 12 constellations of the zodiac, first catalogued by the Greek astronomer Ptolemy in the 2nd century. The constellation’s history, however, dates back to the Bronze Age. Taurus is a large constellation and one of the oldest ones known. In Greek mythology, the constellation is associated with Zeus, who transformed himself into a bull in order to get close to Europa and abduct her.", image_url: "http://www.seasky.org/constellations/assets/images/taurus.jpg", season_id: 1)

constellation_sp1 = Constellation.create(name: "Virgo", description: "Virgo constellation lies in the southern sky. Its name means “virgin” in Latin. The constellation is represented by the symbol ♍. Virgo is one of the 12 zodiac constellations, first catalogued by the Greek astronomer Ptolemy in the 2nd century. It contains Spica, one of the brightest stars in the night sky. It also contains the autumn equinox point, which lies close to the star Beta Virginis. This is one of the two points in the sky (the other being in the constellation Pisces) where the celestial equator intersects with the ecliptic. Virgo is the second largest constellation in the sky. The only constellation larger in size is Hydra.", image_url: "http://www.seasky.org/constellations/assets/images/virgo.jpg", season_id: 2)
constellation_sp2 = Constellation.create(name: "Leo", description: "Leo constellation lies in the northern sky. It is one of the zodiac constellations and one of the largest constellations in the sky. Leo represents the lion and is usually associated with the Nemean lion in Greek mythology. Its symbol is ♌. The constellation was first catalogued by the Greek astronomer Ptolemy in the 2nd century, along with all the other constellations of the zodiac.", image_url: "http://www.seasky.org/constellations/assets/images/leo.jpg", season_id: 2)
constellation_sp3 = Constellation.create(name: "Cancer", description: "Cancer constellation is located in the northern sky. Its name means “the crab” in Latin. Cancer is the faintest of the 12 zodiac constellations. Its symbol is ♋. The constellation was first catalogued by the Greek astronomer Ptolemy in the 2nd century.", image_url: "http://www.seasky.org/constellations/assets/images/cancer.jpg", season_id: 2)
constellation_sp4 = Constellation.create(name: "Ursa Major", description: "Ursa Major constellation lies in the northern sky. Its name means “the great bear,” or “the larger bear,” in Latin. The smaller bear is represented by Ursa Minor. Ursa Major is the largest northern constellation and third largest constellation in the sky. Its brightest stars form the Big Dipper asterism, one of the most recognizable shapes in the sky, also known as the Plough. Ursa Major is well-known in most world cultures and associated with a number of myths. It was one of the constellations catalogued by the Greek astronomer Ptolemy in the 2nd century. In Greek mythology, it is associated with Callisto, a nymph who was turned into a bear by Zeus’ jealous wife Hera.", image_url: "http://www.seasky.org/constellations/assets/images/ursa-major.jpg", season_id: 2)
constellation_sp5 = Constellation.create(name: "Ursa Minor", description: "Ursa Minor constellation lies in the northern sky. The constellation’s name means “the smaller bear,” or “the lesser bear,” in Latin. The Great Bear constellation is represented by its larger neighbor Ursa Major. Ursa Minor was first catalogued by the Greek astronomer Ptolemy in the 2nd century. It is easy to recognize because it contains the famous Little Dipper asterism. Ursa Minor is also notable for marking the location of the north celestial pole, as it is home to Polaris, the North Star, which is located at the end of the dipper’s handle.", image_url: "http://www.seasky.org/constellations/assets/images/ursa-minor.jpg", season_id: 2)

constellation_su1 = Constellation.create(name: "Scorpius", description: "Scorpius constellation lies in the southern sky. It represents the scorpion and is associated with the story of Orion in Greek mythology. Scorpius is one of the zodiac constellations, first catalogued by the Greek astronomer Ptolemy in the 2nd century. Its symbol is ♏. Scorpius pre-dates the Greeks, and is one of the oldest constellations known. The Sumerians called it GIR-TAB, or “the scorpion,” about 5,000 years ago.", image_url: "http://www.seasky.org/constellations/assets/images/scorpius.jpg", season_id: 3)
constellation_su2 = Constellation.create(name: "Sagittarius", description: "Sagittarius constellation lies in the southern sky. It is one of the constellations of the zodiac. It represents the archer. Sagittarius is usually depicted as a centaur holding a bow and arrow. The constellation’s symbol is ♐. It is also associated with Crotus, the satyr who kept company of the Muses on Mount Helicon. Sagittarius is one of the largest southern constellations. It is easy to find because it lies on the Milky Way and its brightest stars form an asterism known as the Teapot. Like other zodiac constellations, Sagittarius was first catalogued by the Greek astronomer Ptolemy in the 2nd century.", image_url: "http://www.seasky.org/constellations/assets/images/sagittarius.jpg", season_id: 3)
constellation_su3 = Constellation.create(name: "Hercules", description: "Hercules constellation is located in the northern sky. It was named after Hercules, the Roman version of the Greek hero Heracles. Heracles, in turn, was often associated with the Sumerian hero Gilgamesh, and the constellation itself has a long history, dating back to Sumerian times. Hercules is the fifth largest constellation in the sky, but has no first magnitude stars. In traditional depictions, the star Ras Algethi (Alpha Herculis) represents Hercules’ head and a prominent asterism, the Keystone, marks his torso, as he stands victoriously on Draco’s head.", image_url: "http://www.seasky.org/constellations/assets/images/hercules.jpg", season_id: 3)
constellation_su4 = Constellation.create(name: "Libra", description: "Libra constellation lies in the southern sky. It is one of the zodiac constellations, first catalogued by Ptolemy in the 2nd century. The constellation’s name means “the weighing scales” in Latin, and Libra is usually depicted as the scales held by the Greek goddess of justice Dike (or Astraea), represented by the neighbouring Virgo constellation.", image_url: "http://www.seasky.org/constellations/assets/images/libra.jpg", season_id: 3)
constellation_su5 = Constellation.create(name: "Ophiuchus", description: "Ophiuchus constellation lies in the southern sky, near the celestial equator. Its name means “the serpent bearer” in Greek. It is pronounced /ˌɒfiːˈjuːkəs/ (off-ee-YOO-cuss). The constellation is associated with the figure of Asclepius, the famous healer in Greek mythology. It was one of the constellations first catalogued by the Greek astronomer Ptolemy in the 2nd century. Sometimes, it is also known by its Latin name, Serpentarius. Ophiuchus is generally depicted as a man holding a snake, represented by the neighboring constellation Serpens, which is divided into two parts by Ophiuchus: Serpens Caput, the snake’s head, and Serpens Cauda, the snake’s tail. The snake is usually depicted coiled around his waist.", image_url: "http://www.seasky.org/constellations/assets/images/ophiuchus.jpg", season_id: 3)

constellation_au1 = Constellation.create(name: "Pices", description: "Pisces constellation lies in the northern sky. Its name means “the fish” (plural) in Latin. Pisces is one of the largest constellations in the sky. It is one of the zodiac constellations, first catalogued by the Greek astronomer Ptolemy in the 2nd century. Its symbol is ♓. Pisces lies between Aries constellation to the east and Aquarius to the west. The two celestial fish represent Venus and Cupid in Roman mythology, who transformed themselves into fish in order to escape the monster Typhon. The Vernal equinox, the point at which the Sun moves to the northern hemisphere across the equator every year, is currently located in Pisces.", image_url: "http://www.seasky.org/constellations/assets/images/pisces.jpg", season_id: 4)
constellation_au2 = Constellation.create(name: "Cassiopeia", description: "Cassiopeia constellation is located in the northern sky. It was named after Cassiopeia, the vain and boastful queen in Greek mythology. The constellation was first catalogued by the Greek astronomer Ptolemy in the 2nd century, along with other constellations in the Perseus family (except Lacerta). Cassiopeia is easily recognizable in the sky because of its distinctive W shape.", image_url: "http://www.seasky.org/constellations/assets/images/cassiopeia.jpg", season_id: 4)
constellation_au3 = Constellation.create(name: "Perseus", description: "Perseus constellation lies in the northern sky, next to Andromeda. It was named after the hero Perseus in Greek mythology. Perseus is one of the larger northern constellations. It was first catalogued by the Greek astronomer Ptolemy in the 2nd century. The constellation is best known for its annual Perseid meteor shower.", image_url: "http://www.seasky.org/constellations/assets/images/perseus.jpg", season_id: 4)
constellation_au4 = Constellation.create(name: "Pegasus", description: "Pegasus constellation lies in the northern hemisphere. It is one of the largest constellations in the sky. It was first catalogued by the Greek astronomer Ptolemy in the 2nd century. The constellation was named after Pegasus, the winged horse in Greek mythology.", image_url: "http://www.seasky.org/constellations/assets/images/pegasus.jpg", season_id: 4)
constellation_au5 = Constellation.create(name: "Aquarius", description: "Aquarius constellation is located in the southern hemisphere. It is one of the 12 zodiac constellations. The constellation’s name means “the water-bearer” (or “cup-bearer”) in Latin and its symbol is ♒, which represents water. Aquarius lies in the region of the sky which is sometimes referred to as the Sea, because it contains a number of other constellations with names associated with water; Pisces (the fish), Eridanus (the river), and Cetus (the whale), among others. Like other zodiac constellations, Aquarius was catalogued by the Greek astronomer Ptolemy in the 2nd century.", image_url: "http://www.seasky.org/constellations/assets/images/aquarius.jpg", season_id: 4)
constellation_au6 = Constellation.create(name: "Aries", description: "Aries constellation is located in the northern hemisphere. Its name means “the ram” in Latin. The symbol for the constellation is ♈ and it represents a ram’s horns. The constellation is usually associated with the story of the Golden Fleece in Greek mythology. Like other zodiac constellations, Aries was first catalogued by the Greek astronomer Ptolemy in the 2nd century.", image_url: "http://www.seasky.org/constellations/assets/images/aries.jpg", season_id: 4)